name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_coverage:
    name: Test & Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test generate script
        run: pnpm generate

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Type check
        run: pnpm typecheck

      - name: Test & Generate Coverage
        run: pnpm -r run test:coverage
