name: Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_examples:
    name: Run Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      # TypeScript examples
      - name: Run TypeScript basic-usage example
        run: pnpm tsx examples/typescript/basic-usage.ts

      - name: Run TypeScript get-latest-block example
        run: pnpm tsx examples/typescript/get-latest-block.ts

      - name: Run TypeScript call-contract-method-view-function example
        run: pnpm tsx examples/typescript/call-contract-method-view-function.ts

      - name: Run TypeScript call-contract-method example
        run: pnpm tsx examples/typescript/call-contract-method.ts

      - name: Run TypeScript status-and-account-demo example
        run: pnpm tsx examples/typescript/status-and-account-demo.ts

      # ESM JavaScript examples
      - name: Run ESM basic-usage example
        run: node examples/javascript-esm/basic-usage.js

      - name: Run ESM status-and-account-demo example
        run: node examples/javascript-esm/status-and-account-demo.js

      # CommonJS JavaScript examples
      - name: Run CJS basic-usage example
        run: node examples/javascript-cjs/basic-usage.js

      - name: Run CJS status-and-account-demo example
        run: node examples/javascript-cjs/status-and-account-demo.js
