name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  # Temporary scope configuration - change these when migrating to @near-js
  PUBLISH_SCOPE: "@psalomo"
  ORIGINAL_SCOPE: "@near-js"

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-upload:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: |
          pnpm pack --pack-destination . -C packages/jsonrpc-types
          pnpm pack --pack-destination . -C packages/jsonrpc-client
      - name: Upload package tarballs to release
        run: |
          for tarball in packages/*/near-js-*.tgz; do
            if [ -f "$tarball" ]; then
              echo "Uploading $tarball"
              gh release upload ${{ needs.release-please.outputs.tag_name }} "$tarball"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build
      
      - name: Prepare and publish packages
        run: |
          if [ "${{ env.PUBLISH_SCOPE }}" != "${{ env.ORIGINAL_SCOPE }}" ]; then
            echo "Publishing to temporary scope ${{ env.PUBLISH_SCOPE }}"
            # Run the publish-temp script to prepare packages
            node scripts/publish-temp.js
            # Publish the prepared packages
            (cd temp-publish/jsonrpc-types && npm publish --access public)
            (cd temp-publish/jsonrpc-client && npm publish --access public)
          else
            echo "Publishing to original scope ${{ env.ORIGINAL_SCOPE }}"
            pnpm -r publish --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
