name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  # Scope configuration for @near-js packages
  PUBLISH_SCOPE: '@near-js'
  ORIGINAL_SCOPE: '@near-js'

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-upload:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: |
          (cd packages/jsonrpc-types && pnpm pack)
          (cd packages/jsonrpc-client && pnpm pack)
      - name: Upload package tarballs to releases
        run: |
          # Upload each tarball to its corresponding release
          for tarball in packages/jsonrpc-types/near-js-jsonrpc-types-*.tgz; do
            if [ -f "$tarball" ]; then
              version=$(basename "$tarball" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
              tag="jsonrpc-types-v$version"
              echo "Uploading $tarball to release $tag"
              gh release upload "$tag" "$tarball" 2>/dev/null || echo "Release $tag not found, skipping"
            fi
          done

          for tarball in packages/jsonrpc-client/near-js-jsonrpc-client-*.tgz; do
            if [ -f "$tarball" ]; then
              version=$(basename "$tarball" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
              tag="jsonrpc-client-v$version"
              echo "Uploading $tarball to release $tag"
              gh release upload "$tag" "$tarball" 2>/dev/null || echo "Release $tag not found, skipping"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Prepare and publish packages
        run: |
          echo "Publishing to ${{ env.PUBLISH_SCOPE }}"
          # Only publish the main packages, not examples
          pnpm --filter "@near-js/jsonrpc-types" publish --access public --no-git-checks
          pnpm --filter "@near-js/jsonrpc-client" publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
