name: Update Generated Code from OpenAPI

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-generated-code:
    name: Update Generated Code from OpenAPI Spec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch OpenAPI spec versions
        run: pnpm fetch-versions

      - name: Generate code for all versions
        run: pnpm generate-all

      - name: Format generated code
        run: pnpm format

      - name: Lint generated code
        run: pnpm lint

      - name: Build packages
        run: pnpm build

      - name: Type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm -r run test:coverage

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: update generated code from OpenAPI spec'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          title: 'feat: update generated code from OpenAPI spec'
          body: |
            This PR contains auto-generated updates from the NEAR Protocol OpenAPI specification.

            ## Changes
            - Discovered and fetched new OpenAPI spec versions
            - Updated TypeScript types for all versions
            - Updated Zod schemas for all versions
            - Updated RPC method mappings
            - Updated client interfaces and functions
            - Updated version-specific exports

            ## Generated Versions
            - Latest version from master branch
            - All tagged releases (v1.0.0, v1.1.0, v1.1.1, etc.)

            ## Validation
            - [x] Version discovery completed successfully
            - [x] Code generation for all versions completed
            - [x] Code formatted with prettier
            - [x] Types compile successfully
            - [x] Tests pass
            - [x] Linting passes
            - [x] Build succeeds
            - [x] Package.json exports updated
            - [x] No breaking changes detected

            All validation steps are run automatically as part of this workflow.
          branch: update-generated-code
          delete-branch: true
